### ISSUE TITLE
License

### ISSUE THREAD

**Issue by mattiascibien** [s-ludwig/sublime-sdlang#2]
Hello,

which is the license of this package?

**Comment by s-ludwig** [comment]
Never though about it, but I'll add a copy of the MIT license.

**Comment by mattiascibien** [comment]
Thnaks. Is it ok if I use some of your code in my project https://github.com/dlang-vscode/dlang-vscode.github.io?

**Comment by s-ludwig** [comment]
Definitely!

**Comment by mattiascibien** [comment]
@s-ludwig thank you so much. You saved our life for SDL files. :+1:
